/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbogui;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author afrin
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        CenteredFrame(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tambahEsteh = new javax.swing.JButton();
        hapusEsteh = new javax.swing.JButton();
        tambahKentangGoreng = new javax.swing.JButton();
        hapusKentangGoreng = new javax.swing.JButton();
        tambahExtraNasi = new javax.swing.JButton();
        hapusExtraNasi = new javax.swing.JButton();
        tambahPaket1 = new javax.swing.JButton();
        hapusPaket1 = new javax.swing.JButton();
        tambahPaket2 = new javax.swing.JButton();
        hapusPaket2 = new javax.swing.JButton();
        tambahPaket3 = new javax.swing.JButton();
        hapusPaket3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jumlahPaket3 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jumlahExtraNasi = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jumlahKentangGoreng = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jumlahEsteh = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jumlahPaket1 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jumlahPaket2 = new javax.swing.JTextArea();
        tipePemesanan = new javax.swing.JComboBox<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        daftarPemesananArea = new javax.swing.JTextArea();
        checkKonfirmasi = new java.awt.Checkbox();
        buttonCekPesanan = new javax.swing.JButton();
        pesanButton = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        textAreaKonfirmasi = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(164, 26, 22));
        setName("mainMenu"); // NOI18N
        setResizable(false);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbogui/dada.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbogui/sayap.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbogui/Es teh.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbogui/kentang.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbogui/paha bawah.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbogui/Nasi.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel7.setText("Es Teh");

        jLabel8.setText("Paket 2 (NASI + AYAM PAHA)");

        jLabel9.setText("Paket 3 (NASI + AYAM SAYAP)");

        jLabel10.setText("Paket 1 (NASI + AYAM DADA)");

        jLabel11.setText("Kentang Goreng");

        jLabel12.setText("Extra Nasi");

        tambahEsteh.setText("TAMBAH");
        tambahEsteh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahEstehActionPerformed(evt);
            }
        });

        hapusEsteh.setText("HAPUS");
        hapusEsteh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusEstehActionPerformed(evt);
            }
        });

        tambahKentangGoreng.setText("TAMBAH");
        tambahKentangGoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahKentangGorengActionPerformed(evt);
            }
        });

        hapusKentangGoreng.setText("HAPUS");
        hapusKentangGoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusKentangGorengActionPerformed(evt);
            }
        });

        tambahExtraNasi.setText("TAMBAH");
        tambahExtraNasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahExtraNasiActionPerformed(evt);
            }
        });

        hapusExtraNasi.setText("HAPUS");
        hapusExtraNasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusExtraNasiActionPerformed(evt);
            }
        });

        tambahPaket1.setText("TAMBAH");
        tambahPaket1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPaket1ActionPerformed(evt);
            }
        });

        hapusPaket1.setText("HAPUS");
        hapusPaket1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPaket1ActionPerformed(evt);
            }
        });

        tambahPaket2.setText("TAMBAH");
        tambahPaket2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPaket2ActionPerformed(evt);
            }
        });

        hapusPaket2.setText("HAPUS");
        hapusPaket2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPaket2ActionPerformed(evt);
            }
        });

        tambahPaket3.setText("TAMBAH");
        tambahPaket3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPaket3ActionPerformed(evt);
            }
        });

        hapusPaket3.setText("HAPUS");
        hapusPaket3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPaket3ActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jumlahPaket3.setEditable(false);
        jumlahPaket3.setColumns(20);
        jumlahPaket3.setRows(5);
        jumlahPaket3.setText("0");
        jScrollPane1.setViewportView(jumlahPaket3);

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jumlahExtraNasi.setEditable(false);
        jumlahExtraNasi.setColumns(20);
        jumlahExtraNasi.setRows(5);
        jumlahExtraNasi.setText("0");
        jScrollPane2.setViewportView(jumlahExtraNasi);

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jumlahKentangGoreng.setEditable(false);
        jumlahKentangGoreng.setColumns(20);
        jumlahKentangGoreng.setRows(5);
        jumlahKentangGoreng.setText("0");
        jScrollPane3.setViewportView(jumlahKentangGoreng);

        jScrollPane4.setBorder(null);
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jumlahEsteh.setEditable(false);
        jumlahEsteh.setColumns(20);
        jumlahEsteh.setRows(5);
        jumlahEsteh.setText("0");
        jScrollPane4.setViewportView(jumlahEsteh);

        jScrollPane5.setBorder(null);
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jumlahPaket1.setEditable(false);
        jumlahPaket1.setColumns(20);
        jumlahPaket1.setRows(5);
        jumlahPaket1.setText("0");
        jScrollPane5.setViewportView(jumlahPaket1);

        jScrollPane6.setBorder(null);
        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jumlahPaket2.setEditable(false);
        jumlahPaket2.setColumns(20);
        jumlahPaket2.setRows(5);
        jumlahPaket2.setText("0");
        jScrollPane6.setViewportView(jumlahPaket2);

        tipePemesanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DINE-IN", "TAKE AWAY" }));

        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        daftarPemesananArea.setColumns(20);
        daftarPemesananArea.setRows(5);
        jScrollPane8.setViewportView(daftarPemesananArea);

        checkKonfirmasi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        checkKonfirmasi.setEnabled(false);
        checkKonfirmasi.setLabel("Konfirmasi pesanan pelanggan");

        buttonCekPesanan.setText("CEK");
        buttonCekPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCekPesananActionPerformed(evt);
            }
        });

        pesanButton.setText("BUAT PESANAN");
        pesanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesanButtonActionPerformed(evt);
            }
        });

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        textAreaKonfirmasi.setEditable(false);
        textAreaKonfirmasi.setColumns(20);
        textAreaKonfirmasi.setRows(5);
        jScrollPane7.setViewportView(textAreaKonfirmasi);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbogui/Menu HIZ.png"))); // NOI18N
        jLabel13.setText("jLabel13");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbogui/Menu HIZ.png"))); // NOI18N
        jLabel14.setText("jLabel14");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbogui/Menu HIZ.png"))); // NOI18N
        jLabel15.setText("jLabel15");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tambahPaket2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hapusPaket2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(210, 210, 210)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tambahKentangGoreng)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hapusKentangGoreng)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(tambahEsteh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hapusEsteh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(tambahPaket1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hapusPaket1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tambahPaket3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hapusPaket3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tambahExtraNasi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hapusExtraNasi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tipePemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonCekPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pesanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tipePemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonCekPesanan))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pesanButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(tambahPaket1)
                                                .addComponent(hapusPaket1)
                                                .addComponent(tambahPaket2)
                                                .addComponent(hapusPaket2)
                                                .addComponent(tambahPaket3)
                                                .addComponent(hapusPaket3))
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(15, 15, 15)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(tambahEsteh)
                                                .addComponent(hapusEsteh)
                                                .addComponent(tambahKentangGoreng)
                                                .addComponent(hapusKentangGoreng)
                                                .addComponent(tambahExtraNasi)
                                                .addComponent(hapusExtraNasi))
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int jumlahPaket1Num = 0;
    int jumlahPaket2Num = 0;
    int jumlahPaket3Num = 0;
    int jumlahEstehNum = 0;
    int jumlahKentangGorengNum = 0;
    int jumlahExtraNasiNum = 0;
    //DISPLAY JUMLAH PESANAN
    
    DaftarMakanan daftarMakanan = new DaftarMakanan();
    DaftarMinuman daftarMinuman = new DaftarMinuman();
    
    //UNTUK MENGHITUNG TOTAL HARGA
    
    int paket1Int;
    int paket2Int;
    int paket3Int;
    int esTehInt;
    int kentangGorengInt;
    int nasiTambahInt;
    
    //MENJUMLAHKAN TOTAL HARGA
    double totalHargaMakan = 0;
    double totalHargaMinum = 0;
    double totalHargaSemua = 0;
    
    //MENAMPILKAN JUMLAH HARGA DARI SETIAP PESANAN
    String paket1StringPrice;
    String paket2StringPrice;
    String paket3StringPrice;
    String esTehStringPrice;
    String kentangGorengStringPrice;
    String nasiTambahStringPrice;
    
    //MENAMPILKAN TEKS SELURUHNYA
    String textHasil = "";
    private void tambahEstehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahEstehActionPerformed
        jumlahEstehNum++;
        jumlahEsteh.setText(""+jumlahEstehNum);
    }//GEN-LAST:event_tambahEstehActionPerformed

    private void hapusEstehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusEstehActionPerformed
        if (jumlahEsteh.getText().equals("0")) {
            jumlahEsteh.setText("0");
        } else {
            jumlahEstehNum--;
            jumlahEsteh.setText(""+jumlahEstehNum);
        }
    }//GEN-LAST:event_hapusEstehActionPerformed

    private void tambahKentangGorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahKentangGorengActionPerformed
        jumlahKentangGorengNum++;
        jumlahKentangGoreng.setText(""+jumlahKentangGorengNum);
    }//GEN-LAST:event_tambahKentangGorengActionPerformed

    private void hapusKentangGorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusKentangGorengActionPerformed
        if (jumlahKentangGoreng.getText().equals("0")) {
            jumlahKentangGoreng.setText("0");
        } else {
            jumlahKentangGorengNum--;
            jumlahKentangGoreng.setText(""+jumlahKentangGorengNum);
        }
    }//GEN-LAST:event_hapusKentangGorengActionPerformed

    private void tambahExtraNasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahExtraNasiActionPerformed
        jumlahExtraNasiNum++;
        jumlahExtraNasi.setText(""+jumlahExtraNasiNum);
    }//GEN-LAST:event_tambahExtraNasiActionPerformed

    private void hapusExtraNasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusExtraNasiActionPerformed
        if (jumlahExtraNasi.getText().equals("0")) {
            jumlahExtraNasi.setText("0");
        } else {
            jumlahExtraNasiNum--;
            jumlahExtraNasi.setText(""+jumlahExtraNasiNum);
        }
    }//GEN-LAST:event_hapusExtraNasiActionPerformed

    private void tambahPaket1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPaket1ActionPerformed
        jumlahPaket1Num++;
        jumlahPaket1.setText(""+jumlahPaket1Num);
    }//GEN-LAST:event_tambahPaket1ActionPerformed

    private void hapusPaket1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPaket1ActionPerformed
        if (jumlahPaket1.getText().equals("0")) {
            jumlahPaket1.setText("0");
        } else {
            jumlahPaket1Num--;
            jumlahPaket1.setText(""+jumlahPaket1Num);
        }
    }//GEN-LAST:event_hapusPaket1ActionPerformed

    private void tambahPaket2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPaket2ActionPerformed
        jumlahPaket2Num++;
        jumlahPaket2.setText(""+jumlahPaket2Num);
    }//GEN-LAST:event_tambahPaket2ActionPerformed

    private void hapusPaket2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPaket2ActionPerformed
        if (jumlahPaket2.getText().equals("0")) {
            jumlahPaket2.setText("0");
        } else {
            jumlahPaket2Num--;
            jumlahPaket2.setText(""+jumlahPaket2Num);
        }
    }//GEN-LAST:event_hapusPaket2ActionPerformed

    private void tambahPaket3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPaket3ActionPerformed
        jumlahPaket3Num++;
        jumlahPaket3.setText(""+jumlahPaket3Num);
    }//GEN-LAST:event_tambahPaket3ActionPerformed

    private void hapusPaket3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPaket3ActionPerformed
        if (jumlahPaket3.getText().equals("0")) {
            jumlahPaket3.setText("0");
        } else {
            jumlahPaket3Num--;
            jumlahPaket3.setText(""+jumlahPaket3Num);
        }
    }//GEN-LAST:event_hapusPaket3ActionPerformed
        
        //CENTER WINDOW
        public void CenteredFrame(javax.swing.JFrame objFrame){
        Dimension objDimension = Toolkit.getDefaultToolkit().getScreenSize();
        int iCoordX = (objDimension.width - objFrame.getWidth()) / 2;
        int iCoordY = (objDimension.height - objFrame.getHeight()) / 2;
        objFrame.setLocation(iCoordX, iCoordY); 
    }
        
    private void buttonCekPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCekPesananActionPerformed
        daftarPemesananArea.setText("");
        textHasil = "";
        totalHargaMakan = 0;
        totalHargaMinum = 0;
        totalHargaSemua = 0;
                
        if (jumlahPaket1Num > 0) {
            totalHargaMakan += jumlahPaket1Num*daftarMakanan.getPaket1();
            paket1StringPrice = "" + jumlahPaket1Num*daftarMakanan.getPaket1();
            textHasil += "Paket 1 - " + jumlahPaket1Num + " - " + paket1StringPrice + "\n";
        }    
        if (jumlahPaket2Num > 0) {
            totalHargaMakan += jumlahPaket2Num*daftarMakanan.getPaket2();
            paket2StringPrice = "" + jumlahPaket2Num*daftarMakanan.getPaket2();
            textHasil += "Paket 2 - " + jumlahPaket2Num + " - " + paket2StringPrice + "\n";
        }
        
        if (jumlahPaket3Num > 0) {
            totalHargaMakan += jumlahPaket3Num*daftarMakanan.getPaket3();
            paket3StringPrice = "" + jumlahPaket3Num*daftarMakanan.getPaket3();
            textHasil += "Paket 3 - " + jumlahPaket3Num + " - " + paket3StringPrice + "\n";
        }
        
        if (jumlahEstehNum > 0) {
            totalHargaMinum += jumlahEstehNum*daftarMinuman.getEsTeh();
            esTehStringPrice = "" + jumlahEstehNum*daftarMinuman.getEsTeh();
            textHasil += "Es Teh - " + jumlahEstehNum + " - " + esTehStringPrice + "\n";
        }
        
        if (jumlahKentangGorengNum > 0) {
            totalHargaMakan += jumlahKentangGorengNum*daftarMakanan.getKentang();
            kentangGorengStringPrice = "" + jumlahKentangGorengNum*daftarMakanan.getKentang();
            textHasil += "Kentang Goreng - " + jumlahKentangGorengNum + " - " +kentangGorengStringPrice + "\n";
        }
        
        if (jumlahExtraNasiNum > 0) {
            totalHargaMakan += jumlahExtraNasiNum*daftarMakanan.getNasiTambah();
            nasiTambahStringPrice = "" + jumlahExtraNasiNum*daftarMakanan.getNasiTambah();
            textHasil += "Tambahan Nasi - " + jumlahExtraNasiNum + " - " + nasiTambahStringPrice + "\n";
        }
        totalHargaMakan *= daftarMakanan.nilaiPajakPesan();
        totalHargaMinum *= daftarMinuman.nilaiPajakPesan();
        totalHargaSemua = totalHargaMakan + totalHargaMinum;
        textHasil += "*****************\n";
        textHasil += tipePemesanan.getSelectedItem() + "\n";
        textHasil += "*****************\n";
        textHasil += "Jumlah Harga Yang Harus Dibayar" + "\n" +"(Termasuk Pajak) : Rp." + totalHargaSemua;
        daftarPemesananArea.setText(textHasil);
        checkKonfirmasi.setEnabled(true);
  
    }//GEN-LAST:event_buttonCekPesananActionPerformed

    private void pesanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanButtonActionPerformed
        if(checkKonfirmasi.getState() == true) {
            textAreaKonfirmasi.setText("");
            Component frame = null;
            JOptionPane.showMessageDialog(frame,
            "PESANAN AKAN SEGERA DIBUAT, \nMOHON TUNGGU SEBENTAR");
        } else {
            textAreaKonfirmasi.setText("ANDA BELUM KONFIRMASI!");
        }
        checkKonfirmasi.setState(false);
        checkKonfirmasi.setEnabled(false);
    }//GEN-LAST:event_pesanButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
                
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCekPesanan;
    private java.awt.Checkbox checkKonfirmasi;
    private javax.swing.JTextArea daftarPemesananArea;
    private javax.swing.JButton hapusEsteh;
    private javax.swing.JButton hapusExtraNasi;
    private javax.swing.JButton hapusKentangGoreng;
    private javax.swing.JButton hapusPaket1;
    private javax.swing.JButton hapusPaket2;
    private javax.swing.JButton hapusPaket3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea jumlahEsteh;
    private javax.swing.JTextArea jumlahExtraNasi;
    private javax.swing.JTextArea jumlahKentangGoreng;
    private javax.swing.JTextArea jumlahPaket1;
    private javax.swing.JTextArea jumlahPaket2;
    private javax.swing.JTextArea jumlahPaket3;
    private javax.swing.JButton pesanButton;
    private javax.swing.JButton tambahEsteh;
    private javax.swing.JButton tambahExtraNasi;
    private javax.swing.JButton tambahKentangGoreng;
    private javax.swing.JButton tambahPaket1;
    private javax.swing.JButton tambahPaket2;
    private javax.swing.JButton tambahPaket3;
    private javax.swing.JTextArea textAreaKonfirmasi;
    private javax.swing.JComboBox<String> tipePemesanan;
    // End of variables declaration//GEN-END:variables
}
